### ISSUE TITLE
"python setup.py install" command fails

### ISSUE THREAD

**Issue by gshimansky** [oleksandr-pavlyk/itt-python#7]
When I run `python setup.py install` I get the following exception:
```
running install
running build
running build_ext
Traceback (most recent call last):
  File "setup.py", line 32, in <module>
    cmdclass={'build_ext': build_ext})
  File "/localdisk/gashiman/miniconda3/envs/intel-python/lib/python3.7/distutils/core.py", line 148, in setup
    dist.run_commands()
  File "/localdisk/gashiman/miniconda3/envs/intel-python/lib/python3.7/distutils/dist.py", line 966, in run_commands
    self.run_command(cmd)
  File "/localdisk/gashiman/miniconda3/envs/intel-python/lib/python3.7/distutils/dist.py", line 985, in run_command
    cmd_obj.run()
  File "/localdisk/gashiman/miniconda3/envs/intel-python/lib/python3.7/distutils/command/install.py", line 545, in run
    self.run_command('build')
  File "/localdisk/gashiman/miniconda3/envs/intel-python/lib/python3.7/distutils/cmd.py", line 313, in run_command
    self.distribution.run_command(command)
  File "/localdisk/gashiman/miniconda3/envs/intel-python/lib/python3.7/distutils/dist.py", line 985, in run_command
    cmd_obj.run()
  File "/localdisk/gashiman/miniconda3/envs/intel-python/lib/python3.7/distutils/command/build.py", line 135, in run
    self.run_command(cmd_name)
  File "/localdisk/gashiman/miniconda3/envs/intel-python/lib/python3.7/distutils/cmd.py", line 313, in run_command
    self.distribution.run_command(command)
  File "/localdisk/gashiman/miniconda3/envs/intel-python/lib/python3.7/distutils/dist.py", line 984, in run_command
    cmd_obj.ensure_finalized()
  File "/localdisk/gashiman/miniconda3/envs/intel-python/lib/python3.7/distutils/cmd.py", line 107, in ensure_finalized
    self.finalize_options()
  File "setup.py", line 18, in finalize_options
    assert self.vtune is not None, "Undefined VTune installation directory"
AssertionError: Undefined VTune installation directory
```

This happens because `install` command doesn't accept `--vtune` command line switch, so `self.vtune` is not set for it. I fixed this locally by setting `self.vtune` to path to my VTune installation directory but this is not a good solution for a general case.

**Comment by rcthomas** [comment]
There's a branch, `install-skip-build` that I think fixes this, I am not sure why it isn't merged.  There's a closed issue indicating that it worked.  The build system here isn't great, admittedly.

**Comment by rcthomas** [comment]
Actually you probably want to look at https://github.com/intel/ittapi
